dist: trusty
sudo: false
language: node_js
node_js: lts/*

install:
- npm ci

cache:
  directories:
  - $HOME/.npm

script:
- npm run build

after_success:
- npm run travis-deploy-once "npm run semantic-release"

# before_deploy:
# - npm run build-demo-site

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: dist/web
    on:
      branch: master

branches:
  except:
  - /^v\d+\.\d+\.\d+$/