---

#-------------------------------------------------------------------------------
# Use this to alter the look of DaVanMonet
#-------------------------------------------------------------------------------
project_info:
  name: DaVanMonet Base
  logo: "/static/logo.svg"
  theme_style: default


#-------------------------------------------------------------------------------
# Path settings
#-------------------------------------------------------------------------------
directories:
  # Path to the pattern library source files
  src: "example"

  # This can be used as the web root when servring as a website
  dist_web: "dist/web"
  
  # This can be used to build a NPM  or NuGet package
  dist_package: "dist/package"
  
  # JS output dir. Relative to dist_web
  js_subDir: "static/js"

  # CSS Output dir. Relative to dist_web
  css_subDir: "static/css"
  
  # Index files will be created here
  indexes: "dist/indexes"

  # Where to look for config files
  configs: "configs"

  # DvM will output css-files to this directory when in dev-mode, if this feature
  # is enabled in compile settings. (see below)
  # Production mode css files will also be copied here during build
  cssCopies: '../DaVanMonetCopyTest'

# If user config is present, the settings in it will override the ones in this file
userconfig: "configs/local-conf.json"


#-------------------------------------------------------------------------------
# Indexing settings
#-------------------------------------------------------------------------------
indexing:
  contentIndexOutput: contentindex.json
  targetIndexOutput: targetindex.json
  keysToOutput:
  - title
  - guid
  - variantid
  - componentid
  - private
  #- requirejs


#-------------------------------------------------------------------------------
# Compiler settings
#-------------------------------------------------------------------------------
compilation:
  compilers:
    less:
      compileIndividualFiles: false
    scss:
      compileIndividualFiles: false
      lint: false
  
  # Targets. Each target will be built to a separate output file.
  # All entried specified in the file array for the target will be included.
  # Files can be of any format that Webpack can understand. By default there
  # are loaders for LESS, SASS and JS configured in DvM
  targets:
    main.css:
    - "**/*.less"
    - "!**/*_inline.less"
    - "!**/*_print.less"
    - "!**/*_exclude.less"
    inline.css:
    - "**/*_inline.less"
    - "**/**/*_inline.less"
    print.css:
    - "**/*_print.less"
    - "**/**/*_print.less"
  
  # Create source maps for JS and CSS
  sourceMaps: true

  # If set to true, CSS files will be emitted to the cssCopies directory during development
  emitCssCopies: true

  # If set to true, assets specified in the assets array (see below), will be copied during build
  copyAssetsToFolder: false

  # Settings for css-minification
  minifycss:
    report: min
    level: 2

  # Settings for PostCSS
  postcss:
    map: true
    processors:
    - name: autoprefixer
      options:
        browsers:
        - last 2 versions


#-------------------------------------------------------------------------------
# Asset settings
#-------------------------------------------------------------------------------
assets:
- src: "example/assets"
  dev_access: "/test/fonts"
  dest: 
  - "dist/web/assets-output"
  - "dist/package/assets-output"


#-------------------------------------------------------------------------------
# Environment settings
#-------------------------------------------------------------------------------
env:
  devSitePort: 9001
  launchBrowser: false
  enableOnSitePreview: true
  cssBreakpoints:
  - title: Mobile
    width: 375
    fromWidth: 0
    toWidth: 375
  - title: Tablet
    width: 768
    fromWidth: 375
    toWidth: 999
  - title: Desktop
    width: 100%
    fromWidth: 1000
    toWidth: 9007199254740990


build:
  mswebdeploy:
    dest: "dist/"
    package: msdeploy.zip
  package:
    files:
    - src: "./configs/package.json"
    - src: "./configs/.npmrc"
      dest: "./.npmrc"
    - src: "./configs/package.nuspec"
      dest: "./package.nuspec"
  web:
    files:
    - src: "./configs/.htaccess"
      dest: "./.htaccess"
    - src: "./configs/Web.config"
      dest: "./Web.config"

structure:
- title: Components
  path: components
- title: General styles
  path: global
- title: Script Modules
  path: modules
- title: Documentation
  path: documentation
  
onsitepreview:
  components:
  - guid: button-guid-used-for-testing-dont-change
    hook: "#main-content > p:nth-child(2)"
