---
project_info:
  name: DaVanMonet
  logo: "/static/logo.png"
  theme_style: default
directories:
  src: "./src"
  jsdest: "./js"
  cssdest: "/css"
  build: "./build"
  dist_web: "./dist/web"
  dist_package: "./dist/package"
  indexes: "./indexes"
  configs: "./configs"
  copycsspath: ''
  copyassetspath: ''
userconfig: "./configs/local-conf.json"
indexing:
  contentindexoutput: contentindex.json
  targetindexoutput: targetindex.json
  keysToOutput:
  - title
  - guid
  - variantid
  - componentid
  - requirejs
compilation:
  compilers:
    less:
      taskname: less
      target: ".less"
      compile: true
      compileIndividualFiles: false
      targets:
        main.css:
        - "**/*.less"
        - "!**/*_inline.less"
        - "!**/*_print.less"
        - "!**/*_exclude.less"
        inline.css:
        - "**/*_inline.less"
        - "**/**/*_inline.less"
        print.css:
        - "**/*_print.less"
        - "**/**/*_print.less"
    scss:
      taskname: sass
      target: ".scss"
      compile: false
      compileIndividualFiles: false
      lint: false
  sourceMaps: true
  copyCompiledCssToFolder: false
  copyAssetsToFolder: false
  minifycss:
    report: min
    level: 2
  postcss:
    map: true
    processors:
    - name: autoprefixer
      options:
        browsers:
        - last 2 versions
developmentenvironment:
  devwebsiteport: 9001
  buildwebsiteport: 9002
  onsitepreviewport: 9003
  livereloadport: 1234
  launchbrowser: false
  cssbreakpoints:
  - id: mobile
    title: Mobile
    width: 375
    fromWidth: 0
    toWidth: 375
  - id: tablet
    title: Tablet
    width: 768
    fromWidth: 376
    toWidth: 999
  - id: desktop
    title: Desktop
    width: 100%
    fromWidth: 1000
    toWidth: 9007199254740990
assets:
- isdirectory: true
  src: "./src/assets"
  dest: "./build/assets"
build:
  mswebdeploy:
    dest: "dist/"
    package: msdeploy.zip
  package:
    files:
    - src: "./package.json"
    - src: "./build/version.json"
      dest: "./"
    - src: "./configs/.npmrc"
      dest: "./"
    - src: "./configs/package.nuspec"
      dest: "./"
  web:
    files:
    - src: "./configs/.htaccess"
      dest: "./"
    - src: "./configs/Web.config"
      dest: "./"
structure:
- title: Components
  path: components
- title: General styles
  path: global
- title: Script Modules
  path: modules
onsitepreview:
  components: []
